---
title: "Dispersion"
description: |
  Post that will link closely to glossary entries and shiny apps all about dispersion, scatter, variance
author:
  - name: Chris Evans
    url: https://www.psyctc.org/R_blog/
    affiliation: PSYCTC.org
    affiliation_url: https://www.psyctc.org/psyctc/
    orcid_id: 0000-0002-4197-4202
# preview: "KStest.png"
date: 2024-03-11
categories:
  - R tricks
  - Distributions
  - Gaussian distribution
output:
  distill::distill_article:
    toc: true
    toc_depth: 4
    hightlight_downlit: true
    self_contained: false
    code_folding: true
    includes: 
      in_header: ../../Gurgle.Rhtml
creative_commons: CC BY-SA
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE)

library(tidyverse)
library(CECPfuns)
library(janitor) # for tabyl()
library(flextable) # for aesthetically OK tables

### set ggplot theme defaults
theme_set(theme_bw())
theme_update(plot.title = element_text(hjust = .5), 
             plot.subtitle = element_text(hjust = .5)) 
```
*Started 11.iii.24*

Dispersion is a useful term in statistics covering the basic idea of how widely scattered values are in a distribution. This blog post is really providing a collection of simulations and plots to illustrate various entries in the [glossary](https://ombook.psyctc.org/glossary ) for the [OMbook](https://ombook.psyctc.org/book/).

Here is a trivial example starting from the [glossary entry for dispersion](https://www.psyctc.org/psyctc/glossary2/dispersion/).

```{r dispersion1}
### from the glossary
tmp <- c(18, 18, 18, 19, 19, 19, 20, 20, 20, 21, 23, 23, 24, 24, 24, 25, 27, 28, 30, 31)
tmp2 <- c(27, 31, 32, 35, 37, 42, 44, 47, 51, 53, 55, 56, 59, 60, 63, 65, 68, 71, 75, 83)
tibble(data1 = tmp,
       data2 = tmp2) -> tmpTib
tmpTib %>%
  pivot_longer(cols = c(data1, data2)) -> tmpTibLong

ggplot(data = tmpTibLong,
       aes(x = value)) +
  facet_grid(cols = vars(name)) +
  geom_histogram()

ggsave(filename = "dispersion1.png", width = 800, height = 600, units = "px")

```