---
title: " An R SAFAQ"
site: distill::distill_website
listing: posts
---
<p></p>
<p></p>
<p></p>
<h1>Using this "Rblog"</h1>
<p></p>
<div class="description">
<p align="left">At the top you should find a search box and a menu.  Probably the best way to find if I have something you want here is to use that search.  However,  you may also find things using the "CATEGORIES" menu on the right of this main page.

Going back to the top right of the menu bar "Welcome" gives you a bit more than this introduction, "About" gives you some geeky background and you can guess what "Copyright/permissions" gives you.  I hope it's all useful, do please [contact me](https://www.psyctc.org/psyctc/contact-me/) if you have suggestions, comments, corrections or requests.</p>  What follows below is the full list of posts in reverse chronological order of creation.  Code used in the posts is in them and revealed by hitting the "Show code", buttons.  Inside code blocks (not all yet) there is a "copy to clipboard" button if you hover your cursor inside the block.</div>
