---
title: "USE"
description: |
  How best to use this site.
author:
  - name: Chris Evans
    url: https://www.psyctc.org/R_blog/
    affiliation: PSYCTC.org
    affiliation_url: https://www.psyctc.org/psyctc/
    orcid_id: 0000-0002-4197-4202
date: 2021-04-10"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
*[Created and first tweaked 10.iv.21, latest edit 7.viii.23]*

The distill system is wonderful but defaults to create a blog so what you see on the landing page is a blog. However, the blog structure is not ideal for repository I am creating here so some advice on using this follows!

At the top (on a big screen, in a menu top right on most small screens I think) on the left you have a search function.  Probably the best way to find if I have something you want here is to use the search.  I think the search uses Gurgle so sometimes the latest posts won't yet be found by the search if Gurgle hasn't found them yet.

On the right of that menu bar "Home", like the logo and title on the left, always brings you back here. Then you have the three main categories of post here:

* Statistical methods
* R methods and tricks
* Non-R geeky things

They will each take you to selections from the full list (below).  You can get more fine grained selections using the "CATEGORIES" menu on the right of this main page.

Going back to the top right of the menu bar "Welcome" gives you a bit more than this introduction, "About" gives you some geeky background and you can guess what "Copyright/permissions" gives you.  I hope it's all useful, do please [contact me](https://www.psyctc.org/psyctc/contact-me/) if you have suggestions, comments, corrections or requests.





